import { ConvexHttpClient } from "convex/browser";
import { api } from "@/convex/_generated/api";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL);

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-pro" });

export async function POST() {
  try {
    console.log("🚀 Starting AI Spending Insights Test...");
    
    // 1. Get users with expenses
    const users = await convex.query(api.inngest.getUsersWithExpenses);
    console.log(`📊 Found ${users.length} users with expenses`);

    if (users.length === 0) {
      return NextResponse.json({
        success: false,
        error: "No users with expenses found. Please add some expenses first.",
        instructions: [
          "1. Go to /dashboard",
          "2. Click 'Add expense'", 
          "3. Add 3-5 sample expenses",
          "4. Come back and try again"
        ]
      });
    }

    const results = [];

    // 2. Process each user
    for (const user of users) {
      console.log(`Processing user: ${user.name} (${user.email})`);
      
      // Get user's monthly expenses
      const expenses = await convex.query(api.inngest.getUserMonthlyExpenses, { 
        userId: user._id 
      });
      
      if (!expenses?.length) {
        console.log(`No expenses found for ${user.name}`);
        continue;
      }

      console.log(`Found ${expenses.length} expenses for ${user.name}`);

      // Build expense data for AI
      const expenseData = {
        expenses,
        totalSpent: expenses.reduce((sum, e) => sum + e.amount, 0),
        categories: expenses.reduce((cats, e) => {
          cats[e.category ?? "uncategorised"] = (cats[e.category] ?? 0) + e.amount;
          return cats;
        }, {}),
      };

      // Create AI prompt
      const prompt = `
As a financial analyst, review this user's spending data and provide insightful observations and suggestions.
Focus on spending patterns, category breakdowns, and actionable advice for better financial management.
Use a friendly, encouraging tone. Format your response in HTML for an email.

User spending data:
${JSON.stringify(expenseData, null, 2)}

Provide your analysis in these sections:
1. Monthly Overview
2. Top Spending Categories  
3. Unusual Spending Patterns (if any)
4. Saving Opportunities
5. Recommendations for Next Month
      `.trim();

      try {
        console.log(`🧠 Sending data to Gemini AI for ${user.name}...`);
        
        // Call Gemini AI
        const aiResponse = await model.generateContent(prompt);
        const htmlBody = aiResponse.response.candidates[0]?.content.parts[0]?.text ?? "";

        console.log(`✅ AI generated insights for ${user.name}`);
        console.log("AI Response Preview:", htmlBody.substring(0, 200) + "...");

        // Send email
        await convex.action(api.email.sendEmail, {
          to: user.email,
          subject: "🤖 Your AI-Powered Monthly Spending Insights - Splitely",
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h1 style="color: #16a34a;">Your Monthly Financial Insights</h1>
              <p>Hi ${user.name},</p>
              <p>Here's your personalized spending analysis powered by AI:</p>
              <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
                ${htmlBody}
              </div>
              <p style="color: #6b7280; font-size: 14px;">
                This analysis was generated by Splitely's AI assistant to help you make better financial decisions.
              </p>
            </div>
          `,
          apiKey: process.env.RESEND_API_KEY,
        });

        console.log(`📧 Email sent to ${user.email}`);
        results.push({ 
          userId: user._id, 
          name: user.name,
          email: user.email,
          success: true,
          expenseCount: expenses.length,
          totalSpent: expenseData.totalSpent
        });
      } catch (err) {
        console.error(`❌ Error processing ${user.name}:`, err.message);
        results.push({
          userId: user._id,
          name: user.name,
          success: false,
          error: err.message,
        });
      }
    }

    // Return summary
    const summary = {
      processed: results.length,
      success: results.filter((r) => r.success).length,
      failed: results.filter((r) => !r.success).length,
      results: results
    };

    console.log("🎯 Test Summary:", summary);

    return NextResponse.json({
      success: true,
      message: "AI insights generated successfully!",
      summary,
      instructions: [
        "1. Check your email for AI-generated insights",
        "2. The AI analyzed your recent expenses and spending patterns",
        "3. You should receive personalized financial recommendations"
      ]
    });

  } catch (error) {
    console.error("❌ Error in AI test:", error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    message: "AI Testing Endpoint",
    instructions: "Send a POST request to trigger AI spending insights test",
    example: "curl -X POST http://localhost:3000/api/test-ai"
  });
}